name: Build/publish Docker image & rebuild/restart service

description: |
  Github Action used to accomplish two things
   1. Build & publish the Docker image of a Digbee service to the Github's Docker registry.
   2. Rebuild and restart the service container to use the new image.

inputs:
  github-token:
    description: Github Token
    required: true

  ssh-server:
    description: SSH server IP
    required: true

  ssh-user:
    description: SSH username
    required: true

  ssh-key:
    description: SSH private key
    required: true

  docker-compose-file:
    description: Path to the env-specific docker-compose file in @thedigbee/devops to be used to run the containers with
    required: true

  ssh-command-timeout:
    description: Timeout for SSH command (see https://github.com/appleboy/ssh-action)
    default: 10m

runs:
  using: composite
  steps:
    - name: Set branch name vars
      id: vars
      shell: bash
      run: |
        # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions/58034787
        echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
        echo ::set-output name=repository_name::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=sha

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Execute commands on SSH host
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ inputs.ssh-server }}
        USERNAME: ${{ inputs.ssh-user }}
        KEY: ${{ inputs.ssh-key }}
        command_timeout: ${{ inputs.ssh-command-timeout }}
        script: |
          cd ~/src/devops
          sudo docker pull ghcr.io/${{github.repository_owner}}/${{ steps.vars.outputs.repository_name }}:${{ steps.vars.outputs.branch_name }}
          COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 sudo docker-compose \
            -f docker-compose.yml \
            -f ${{ inputs.docker_compose_file }} \
            up --force-recreate -d --remove-orphans \
            digbee-${{ steps.vars.outputs.repository_name }}
