name: bump-prerelease

description: |
  Bumps prerelease version.
  Depends on actions:
    - actions/checkout
    - actions/setup-node or thedigbee/actions/node-nvmrc

inputs:
  author-name:
    description: Name of the author of the bump commit
    required: true
    default: "@thedigbee/actions"
  author-email:
    description: Email of the author of the bump commit
    required: true
    default: "<>"
  prerelease-id:
    description: Prerelease identifier (https://docs.npmjs.com/cli/v7/commands/npm-version#preid)
    default: beta
  tag-commit:
    description: If enabled, tags the commit with the prerelease version
    default: false
  branch_ref:
    description: Git branch. Defaults to the value `github.head_ref`
    required: true
    default: ${{ github.head_ref }}

outputs:
  branch-name:
    description: Sanitized branch name
    value: ${{ steps.sanitize-step.outputs.sanitized }}

  version:
    description: Prerelease version
    value: ${{ steps.versioning-step.outputs.version }}

  prerelease-tag:
    description: Prerelease tag, "${prerelease ID}-${sanitizied branch name}"
    value: ${{ steps.versioning-step.outputs.prerelease-tag }}

runs:
  using: composite
  steps:
    - id: sanitize-step
      uses: thedigbee/actions/sanitize@master
      with:
        value: ${{ inputs.branch_ref }}

    - id: versioning-step
      shell: bash
      run: |
        PRERELEASE_TAG="${{ inputs.prerelease-id }}-${{ steps.sanitize-step.outputs.sanitized }}"

        PLACEHOLDER="%s"
        COMMIT_MESSAGE_TEMPLATE="ci(prerelease): $PLACEHOLDER"

        git config user.name "${{ inputs.author-name }}"
        git config user.email "${{ inputs.author-email }}"

        if [[ "${{ inputs.tag-commit }}" == "true" ]]; then
          VERSION=$(npm version prerelease --preid="$PRERELEASE_TAG" -m "$COMMIT_MESSAGE_TEMPLATE")
        else
          VERSION=$(npm version prerelease --preid="$PRERELEASE_TAG" -m "$COMMIT_MESSAGE_TEMPLATE" --no-git-tag-version)

          # strips first character "v" of $VERSION
          VERSION=${VERSION:1}

          git commit -am "$(echo $COMMIT_MESSAGE_TEMPLATE | sed "s/$PLACEHOLDER/$VERSION/g")"
        fi

        git push --tags origin "${{ inputs.branch_ref }}"

        echo "::set-output name=version::$VERSION"
        echo "::set-output name=prerelease-tag::$PRERELEASE_TAG"
