name: node-nvmrc

description: Wrapper around actions/setup-node@v2 to use version from .nvmrc

outputs:
  version:
    description: Node version from the .nvmrc file
    value: ${{ steps.read-nvmrc-step.outputs.version }}

runs:
  using: composite
  steps:
    - id: read-nvmrc-step
      name: Read .nvmrc file
      shell: bash
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.read-nvmrc-step.outputs.version }}
        registry-url: https://npm.pkg.github.com
        scope: thedigbee
