name: Prerelease

on:
  pull_request:
    branches: [master]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: should-skip-step
        uses: ./should-skip

      - if: steps.should-skip-step.outputs.skip == 'false'
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3
          registry-url: https://npm.pkg.github.com
          scope: thedigbee

      - #if: steps.should-skip-step.outputs.skip == 'false'
        id: sanitize-step
        uses: ./sanitize
        with:
          value: ${{ github.head_ref }}

      - if: steps.should-skip-step.outputs.skip == 'false'
        name: Version prerelease and commit it.
        run: |
          VERSION=$(npm version --no-git-tag-version prerelease --preid=beta-"${{ steps.sanitize-step.outputs.sanitized }}")
          git config --global user.name 'cidigbee'
          git config --global user.email 'ci@thedigbee.com'
          git commit -am "ci(prerelease): $VERSION"
          git push origin "${{ github.head_ref }}"

      - if: steps.should-skip-step.outputs.skip == 'false'
        name: Publishes prerelease
        run: |
          echo "Prerelease tag is: 'next-${{ steps.sanitize-step.outputs.sanitized }}'"
          # npm publish ./build --tag "next-${{ steps.sanitize-step.outputs.sanitized }}"
