name: Prerelease

on:
  pull_request:
    branches: [master]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: should-skip-step
        uses: thedigbee/actions/should-skip@v0.0.1-beta-feat-should-skip-and-prerelease.4

      - if: steps.should-skip-step.outputs.skip == 'false'
        uses: thedigbee/actions/node-nvmrc@v0.0.1-beta-feat-should-skip-and-prerelease.4

      - if: steps.should-skip-step.outputs.skip == 'false'
        uses: thedigbee/actions/bump-prerelease@v0.0.1-beta-feat-should-skip-and-prerelease.4
        with:
          tag-commit: true
