name: Prerelease

on:
  pull_request:
    branches: [master]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - id: should-skip-step
        uses: ./should-skip

      - if: steps.should-skip-step.outputs.skip == 'false'
        id: bump-prerelease-step
        uses: ./bump-prerelease

      - if: steps.should-skip-step.outputs.skip == 'false'
        name: Publishes prerelease
        run: |
          echo "Prerelease tag is: 'next-${{ steps.bump-prerelease-step.outputs.branch-name }}'"
          # npm publish ./build --tag "next-${{ steps.bump-prerelease-step.outputs.branch-name }}"
