name: Prerelease

on:
  pull_request:
    branches: [master]

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./should-skip

      - if: env.DO_PRERELEASE == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.3
          registry-url: https://npm.pkg.github.com
          scope: thedigbee

      - if: env.DO_PRERELEASE == 'true'
        run: npm ci

      - if: env.DO_PRERELEASE == 'true'
        run: npm run lint

      - if: env.DO_PRERELEASE == 'true'
        run: npm run test

      - if: env.DO_PRERELEASE == 'true'
        name: Sanitize branch name
        run: |
          echo "BRANCH_NAME=$(sed -E 's/[^[:alnum:]]+/-/g' <<<"${{ github.head_ref }}")" >> $GITHUB_ENV

      - if: env.DO_PRERELEASE == 'true'
        name: Version prerelease and commit it.
        run: |
          VERSION=$(npm version --no-git-tag-version prerelease --preid=beta-"${{ env.BRANCH_NAME }}")
          git config --global user.name 'cidigbee'
          git config --global user.email 'ci@thedigbee.com'
          git commit -am "ci(prerelease): $VERSION"
          git push origin "${{ github.head_ref }}"

      - if: env.DO_PRERELEASE == 'true'
        run: npm run build

      - if: env.DO_PRERELEASE == 'true'
        name: Publishes prerelease
        run: |
          echo "Prerelease tag is: 'next-${{ env.BRANCH_NAME }}'"
          npm publish ./build --tag "next-${{ env.BRANCH_NAME }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CIDIGBEE_PUBLISH_TOKEN }}
